name: deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Twilio callbox service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Create .env
        uses: spicypizza/create-envfile@v1.3
        with:
          envkey_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          envkey_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          envkey_SENTRY_DSN: ${{ env.SENTRY_DSN }}
          envkey_KEYWAY_SERVICE_URL: ${{ env.KEYWAY_SERVICE_URL }}
          envkey_KEYWAY_FALLBACK_NUMBER: ${{ env.KEYWAY_FALLBACK_NUMBER }}
      - run: yarn
      - run: yarn deploy
      - run: yarn activate
